// GoSIM-WhiteLabel-Vuejs/src/views/packagesList/components/SummaryForm.vue
<template>
  <div class="bg-gray-50 border border-gray-100 rounded-3xl p-4 md:p-6">
    <h3 class="hidden md:block text-lg font-bold text-gray-900 mb-5">{{ $t("orders.summary") }}</h3>

    <form v-if="selectedPackage.id" class="md:space-y-2" @submit.prevent="submitOrder">
      <!-- Selected Package Specs -->
      <div class="hidden md:flex items-center gap-4 bg-white border border-gray-100 p-4 rounded-2xl">
        <img :src="location.image" class="w-11 h-11 object-cover rounded-full" />
        <div>
          <p class="font-bold text-sm text-gray-900">{{ location.name }}</p>
          <p class="text-xs text-gray-500 font-medium mt-0.5">
            {{ selectedPackage.duration === 1 ? $t("plans.duration.unlimitedData") + ' ' +
              $formatBytes(selectedPackage.volume) :
              $formatBytes(selectedPackage.volume) }}
          </p>
        </div>
      </div>

      <!-- Quantity Modifier -->
      <div :class="['md:flex', step === 1 ? 'flex' : 'hidden']"
        class="items-center justify-between pt-1 pb-2 md:pt-3 md:pb-6 border-b border-gray-200/50">
        <span class="text-sm font-bold text-gray-700">{{ $t("orders.quantity") }}</span>
        <div class="flex items-center gap-3">
          <button type="button"
            class="w-8 h-8 border border-gray-300 rounded-xl flex items-center justify-center bg-white hover:bg-gray-50 text-gray-600 transition-colors"
            @click="quantity > 1 ? $emit('update:quantity', quantity - 1) : null">
            <i class="fa-solid fa-minus text-xs"></i>
          </button>
          <span class="font-black text-base w-6 text-center text-gray-900">{{ quantity }}</span>
          <button type="button"
            class="w-8 h-8 border border-gray-300 rounded-xl flex items-center justify-center bg-white hover:bg-gray-50 text-gray-600 transition-colors"
            @click="$emit('update:quantity', quantity + 1)">
            <i class="fa-solid fa-plus text-xs"></i>
          </button>
        </div>
      </div>

      <!-- Days Modifier -->
      <div v-if="selectedPackage.duration === 1"
        class="hidden md:flex items-center justify-between pt-3 pb-6 border-b border-gray-200/50">
        <span class="text-sm font-bold text-gray-700">{{ days === 1 ? $t("plans.duration.day") : $t("orders.days")
          }}</span>
        <div class="flex items-center gap-3">
          <button type="button"
            class="size-8 border border-gray-300 rounded-xl flex items-center justify-center bg-white hover:bg-gray-50 text-gray-600 transition-colors"
            @click="days > 1 ? $emit('update:days', days - 1) : null">
            <i class="fa-solid fa-minus text-xs"></i>
          </button>
          <span class="font-black text-base w-6 text-center text-gray-900">{{ days }}</span>
          <button type="button"
            class="size-8 border border-gray-300 rounded-xl flex items-center justify-center bg-white hover:bg-gray-50 text-gray-600 transition-colors"
            @click="days < 30 ? $emit('update:days', days + 1) : null">
            <i class="fa-solid fa-plus text-xs"></i>
          </button>
        </div>
      </div>

      <!-- Subtotal -->
      <div class="hidden md:flex items-center justify-between pt-3 pb-6 border-b border-gray-200/50">
        <span class="text-sm font-bold text-gray-700">{{ $t("orders.subTotal") }}</span>
        <div class="flex flex-col items-end">
          <span class="font-black text-base text-gray-900">
            {{ $currencyFormatter(getDiscountedPrice(selectedPackage, selectedPackage.duration === 1 ? days : 1) *
              quantity) }}
          </span>
          <span v-if="selectedPackage.duration === 1 && getDiscount(selectedPackage, days) > 0"
            class="text-xs line-through text-gray-400">
            {{ $currencyFormatter(selectedPackage.price * days * quantity) }}
          </span>
        </div>
      </div>

      <!-- Customer Form (Visible on desktop, and on mobile if step === 2) -->
      <div :class="['md:block', step === 1 ? 'hidden' : 'block']"
        class="pt-3 pb-6 md:border-b border-gray-200/50 space-y-3">
        <div class="flex items-center justify-between">
          <h4 class="text-sm font-bold text-gray-900 mb-2">{{ $t("orders.billingInformation") }}</h4>
          <button v-if="step === 2" @click="step = 1"
            class="inline-flex items-center justify-center text-gray-500 border rounded-xl border-gray-300 bg-white size-8">
            <i class="fa-solid fa-xmark text-xs"></i>
          </button>
        </div>

        <div>
          <label class="block text-xs font-bold text-gray-700 mb-2">{{ $t("orders.deliveryMethod", "Delivery Method")
            }}</label>
          <div class="flex items-center gap-4">
            <label class="flex items-center gap-2 text-sm cursor-pointer">
              <input type="radio" v-model="deliveryMethod" value="email" class="text-primary focus:ring-primary" />
              <span>{{ $t("orders.email", "Email") }}</span>
            </label>
            <label class="flex items-center gap-2 text-sm cursor-pointer">
              <input type="radio" v-model="deliveryMethod" value="whatsapp" class="text-primary focus:ring-primary" />
              <span>{{ $t("orders.whatsapp", "WhatsApp") }}</span>
            </label>
            <label class="flex items-center gap-2 text-sm cursor-pointer">
              <input type="radio" v-model="deliveryMethod" value="phone" class="text-primary focus:ring-primary" />
              <span>{{ $t("orders.sms", "SMS") }}</span>
            </label>
          </div>
        </div>

        <div>
          <label class="block text-xs font-bold text-gray-700 mb-1">{{ $t("orders.fullName") }} <span
              class="text-red-500">*</span></label>
          <input v-model="customer.name" type="text" required
            class="w-full bg-white border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
            :placeholder="$t('orders.namePlaceholder')" />
        </div>

        <div>
          <label class="block text-xs font-bold text-gray-700 mb-1">{{ $t("orders.emailAddress") }} <span
              class="text-red-500">*</span></label>
          <input v-model="customer.email" type="email" required
            class="w-full bg-white border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
            :placeholder="$t('orders.emailPlaceholder')" />
        </div>

        <div v-if="deliveryMethod === 'whatsapp' || deliveryMethod === 'phone'">
          <label class="block text-xs font-bold text-gray-700 mb-1">{{ $t("orders.phoneNumber") }} <span
              class="text-red-500">*</span></label>
          <div class="flex gap-2">
            <select v-model="selectedCoutryCode" type="text"
              class="w-24 bg-white border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50">
              <option v-for="country in countries" :key="country.code" :value="country.code">
                {{ country.code }}
              </option>
            </select>
            <input v-model="customer.phone" type="tel" required
              class="w-full bg-white border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
              :placeholder="$t('orders.phonePlaceholder')" pattern="[567][0-9]{8}" maxlength="9" />
          </div>
        </div>
      </div>

      <!-- Total -->
      <div class="hidden md:flex items-center justify-between pt-3 pb-6 border-gray-200/50">
        <span>{{ $t("orders.total") }}</span>
        <div class="flex flex-col items-end">
          <span class="font-black text-lg text-gray-900">
            {{ $currencyFormatter(getDiscountedPrice(selectedPackage, selectedPackage.duration === 1 ? days : 1) *
              quantity) }}
          </span>
          <span v-if="selectedPackage.duration === 1 && getDiscount(selectedPackage, days) > 0"
            class="text-sm line-through text-gray-400">
            {{ $currencyFormatter(selectedPackage.price * days * quantity) }}
          </span>
        </div>
      </div>

      <!-- Order Submission -->
      <button type="submit" class="btn-primary w-full hidden md:flex mt-4" :disabled="loading">
        <i v-if="loading" class="fa-solid fa-circle-notch fa-spin"></i>
        <span v-else>{{ $t("orders.placeOrder") }}</span>
      </button>

      <!-- Mobile Actions -->
      <button v-if="step === 1" type="button" @click="step = 2" class="btn-primary w-full md:hidden mt-2">
        {{ $t("common.continue") }}
      </button>
      <button v-else type="submit" class="btn-primary w-full md:hidden mt-2" :disabled="loading">
        <i v-if="loading" class="fa-solid fa-circle-notch fa-spin"></i>
        <template v-else>
          {{ $t("orders.placeOrder") }} {{
            $currencyFormatter(getDiscountedPrice(selectedPackage, selectedPackage.duration === 1 ? days : 1) *
              quantity) }}
        </template>
      </button>

      <!-- Exclusive notice -->
      <p class="text-[11px] text-gray-400 font-semibold text-center hidden md:block mt-2">
        {{ $t("orders.appExclusiveRates") }}
      </p>
    </form>

    <!-- Empty State -->
    <div v-else class="text-center py-10 text-gray-500 text-sm font-medium">
      <i class="fa-light fa-wallet text-3xl text-gray-300 mb-3 block"></i>
      {{ $t('orders.emptySummaryState') }}
    </div>
  </div>
</template>

<script>
export default {
  props: {
    selectedPackage: Object,
    quantity: Number,
    days: Number,
    location: Object,
    loading: {
      type: Boolean,
      default: true
    }
  },
  emits: ['submit', 'update:quantity', 'update:days'],
  data() {
    return {
      step: 1,
      deliveryMethod: 'email',
      customer: {
        name: '',
        email: '',
        phone: '',
        whatsapp: ''
      },
      selectedCoutryCode: "+213",
      countries: [
        {
          code: "+213",
          name: "algeria",
        },
      ]
      // countries: [
      //   {
      //     code: "+971",
      //     name: "United Arab Emirates",
      //   },
      //   {
      //     code: "+91",
      //     name: "India",
      //   },
      //   {
      //     code: "+1",
      //     name: "United States",
      //   },
      //   {
      //     code: "+44",
      //     name: "United Kingdom",
      //   },
      //   {
      //     code: "+49",
      //     name: "Germany",
      //   },
      //   {
      //     code: "+81",
      //     name: "Japan",
      //   },
      //   {
      //     code: "+33",
      //     name: "France",
      //   },
      //   {
      //     code: "+39",
      //     name: "Italy",
      //   },
      //   {
      //     code: "+34",
      //     name: "Spain",
      //   },
      //   {
      //     code: "+55",
      //     name: "Brazil",
      //   },
      // ],
    }
  },
  methods: {
    getDiscount(pack, days) {
      if (!pack.daily_discounts || !pack.daily_discounts.length) return 0;
      let applicable = pack.daily_discounts.filter(d => days >= d.day);
      if (applicable.length > 0) {
        return Math.max(...applicable.map(d => d.discount));
      }
      return 0;
    },
    getDiscountedPrice(pack, days) {
      let total = pack.price * days;
      let discount = this.getDiscount(pack, days);
      return total * (1 - discount / 100);
    },
    submitOrder() {
      const payload = {
        name: this.customer.name,
        email: this.customer.email,
      };

      if (this.deliveryMethod === 'phone') {
        payload.phone = this.selectedCoutryCode + this.customer.phone;
      } else if (this.deliveryMethod === 'whatsapp') {
        payload.whatsapp = this.selectedCoutryCode + this.customer.phone;
      }

      this.$emit('submit', payload);
    }
  }
}
</script>

// GoSIM-WhiteLabel-Reactjs/src/views/SummaryForm.tsx
import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { currencyFormatter, formatBytes } from '../utils/utils';

interface SummaryFormProps {
  selectedPackage: any;
  quantity: number;
  days: number;
  location: any;
  loading: boolean;
  onQuantityChange: (val: number) => void;
  onDaysChange: (val: number) => void;
  onFormSubmit: (customerData: any) => void;
}

export const SummaryForm: React.FC<SummaryFormProps> = ({
  selectedPackage,
  quantity,
  days,
  location,
  loading,
  onQuantityChange,
  onDaysChange,
  onFormSubmit,
}) => {
  const { language, currency, t } = useApp();
  const [step, setStep] = useState(1);
  const [deliveryMethod, setDeliveryMethod] = useState<'email' | 'whatsapp' | 'phone'>('email');
  const [customer, setCustomer] = useState({ name: '', email: '', phone: '' });
  const [selectedCountryCode, setSelectedCountryCode] = useState('+213');

  const countries = [{ code: '+213', name: 'Algeria' }];

  const getDiscount = (pack: any, daysCount: number): number => {
    if (!pack?.daily_discounts?.length) return 0;
    const applicable = pack.daily_discounts.filter((d: any) => daysCount >= d.day);
    if (applicable.length > 0) {
      return Math.max(...applicable.map((d: any) => d.discount));
    }
    return 0;
  };

  const getDiscountedPrice = (pack: any, daysCount: number): number => {
    if (!pack) return 0;
    const total = pack.price * daysCount;
    const discount = getDiscount(pack, daysCount);
    return total * (1 - discount / 100);
  };

  const submitOrder = (e: React.FormEvent) => {
    e.preventDefault();
    const payload: any = {
      name: customer.name,
      email: customer.email,
    };

    if (deliveryMethod === 'phone') {
      payload.phone = selectedCountryCode + customer.phone;
    } else if (deliveryMethod === 'whatsapp') {
      payload.whatsapp = selectedCountryCode + customer.phone;
    }

    onFormSubmit(payload);
  };

  const hasSelectedPackage = selectedPackage && selectedPackage.id;
  const activeDays = selectedPackage?.duration === 1 ? days : 1;
  const singlePrice = getDiscountedPrice(selectedPackage, activeDays);
  const totalPrice = singlePrice * quantity;
  const originalPrice = selectedPackage ? selectedPackage.price * activeDays * quantity : 0;
  const hasDiscountVal = selectedPackage?.duration === 1 && getDiscount(selectedPackage, days) > 0;

  return (
    <div className="bg-gray-50 border border-gray-100 rounded-3xl p-4 md:p-6">
      <h3 className="hidden md:block text-lg font-bold text-gray-900 mb-5">{t('orders.summary')}</h3>

      {hasSelectedPackage ? (
        <form onSubmit={submitOrder} className="md:space-y-2">
          {/* Selected Package Specs */}
          <div className="hidden md:flex items-center gap-4 bg-white border border-gray-100 p-4 rounded-2xl">
            <img src={location?.image} alt={location?.name} className="w-11 h-11 object-cover rounded-full shrink-0" />
            <div className="text-left min-w-0">
              <p className="font-bold text-sm text-gray-900 truncate">{location?.name}</p>
              <p className="text-xs text-gray-500 font-medium mt-0.5 truncate">
                {selectedPackage?.duration === 1
                  ? `${t('plans.duration.unlimitedData')} ${formatBytes(selectedPackage?.volume, language)}`
                  : formatBytes(selectedPackage?.volume, language)}
              </p>
            </div>
          </div>

          {/* Quantity Modifier */}
          <div
            className={`items-center justify-between pt-1 pb-2 md:pt-3 md:pb-6 border-b border-gray-200/50 ${
              step === 1 ? 'flex' : 'hidden md:flex'
            }`}
          >
            <span className="text-sm font-bold text-gray-700">{t('orders.quantity')}</span>
            <div className="flex items-center gap-3">
              <button
                type="button"
                className="w-8 h-8 border border-gray-300 rounded-xl flex items-center justify-center bg-white hover:bg-gray-50 text-gray-600 transition-colors cursor-pointer"
                onClick={() => quantity > 1 && onQuantityChange(quantity - 1)}
              >
                <i className="fa-solid fa-minus text-xs" />
              </button>
              <span className="font-black text-base w-6 text-center text-gray-900">{quantity}</span>
              <button
                type="button"
                className="w-8 h-8 border border-gray-300 rounded-xl flex items-center justify-center bg-white hover:bg-gray-50 text-gray-600 transition-colors cursor-pointer"
                onClick={() => onQuantityChange(quantity + 1)}
              >
                <i className="fa-solid fa-plus text-xs" />
              </button>
            </div>
          </div>

          {/* Days Modifier */}
          {selectedPackage?.duration === 1 && (
            <div className={`hidden md:flex items-center justify-between pt-3 pb-6 border-b border-gray-200/50`}>
              <span className="text-sm font-bold text-gray-700">
                {days === 1 ? t('plans.duration.day') : t('orders.days')}
              </span>
              <div className="flex items-center gap-3">
                <button
                  type="button"
                  className="w-8 h-8 border border-gray-300 rounded-xl flex items-center justify-center bg-white hover:bg-gray-50 text-gray-600 transition-colors cursor-pointer"
                  onClick={() => days > 1 && onDaysChange(days - 1)}
                >
                  <i className="fa-solid fa-minus text-xs" />
                </button>
                <span className="font-black text-base w-6 text-center text-gray-900">{days}</span>
                <button
                  type="button"
                  className="w-8 h-8 border border-gray-300 rounded-xl flex items-center justify-center bg-white hover:bg-gray-50 text-gray-600 transition-colors cursor-pointer"
                  onClick={() => days < 30 && onDaysChange(days + 1)}
                >
                  <i className="fa-solid fa-plus text-xs" />
                </button>
              </div>
            </div>
          )}

          {/* Subtotal */}
          <div className="hidden md:flex items-center justify-between pt-3 pb-6 border-b border-gray-200/50">
            <span className="text-sm font-bold text-gray-700">{t('orders.subTotal')}</span>
            <div className="flex flex-col items-end">
              <span className="font-black text-base text-gray-900">
                {currencyFormatter(totalPrice, currency)}
              </span>
              {hasDiscountVal && (
                <span className="text-xs line-through text-gray-400">
                  {currencyFormatter(originalPrice, currency)}
                </span>
              )}
            </div>
          </div>

          {/* Customer Billing Form */}
          <div className={`pt-3 pb-6 md:border-b border-gray-200/50 space-y-3 ${step === 1 ? 'hidden md:block' : 'block'}`}>
            <div className="flex items-center justify-between">
              <h4 className="text-sm font-bold text-gray-900 mb-2">{t('orders.billingInformation')}</h4>
              {step === 2 && (
                <button
                  type="button"
                  onClick={() => setStep(1)}
                  className="md:hidden inline-flex items-center justify-center text-gray-500 border rounded-xl border-gray-300 bg-white size-8 cursor-pointer"
                >
                  <i className="fa-solid fa-xmark text-xs" />
                </button>
              )}
            </div>

            {/* Delivery Method */}
            <div>
              <label className="block text-xs font-bold text-gray-700 mb-2">{t('orders.deliveryMethod')}</label>
              <div className="flex items-center gap-4">
                <label className="flex items-center gap-2 text-sm cursor-pointer select-none">
                  <input
                    type="radio"
                    checked={deliveryMethod === 'email'}
                    onChange={() => setDeliveryMethod('email')}
                    className="text-primary focus:ring-primary"
                  />
                  <span>{t('orders.email')}</span>
                </label>
                <label className="flex items-center gap-2 text-sm cursor-pointer select-none">
                  <input
                    type="radio"
                    checked={deliveryMethod === 'whatsapp'}
                    onChange={() => setDeliveryMethod('whatsapp')}
                    className="text-primary focus:ring-primary"
                  />
                  <span>{t('orders.whatsapp')}</span>
                </label>
                <label className="flex items-center gap-2 text-sm cursor-pointer select-none">
                  <input
                    type="radio"
                    checked={deliveryMethod === 'phone'}
                    onChange={() => setDeliveryMethod('phone')}
                    className="text-primary focus:ring-primary"
                  />
                  <span>{t('orders.sms')}</span>
                </label>
              </div>
            </div>

            {/* Full Name */}
            <div className="flex flex-col gap-1 text-left">
              <label className="block text-xs font-bold text-gray-700">
                {t('orders.fullName')} <span className="text-red-500">*</span>
              </label>
              <input
                value={customer.name}
                onChange={(e) => setCustomer({ ...customer, name: e.target.value })}
                type="text"
                required
                className="w-full bg-white border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 text-left"
                placeholder={t('orders.namePlaceholder')}
              />
            </div>

            {/* Email Address */}
            <div className="flex flex-col gap-1 text-left">
              <label className="block text-xs font-bold text-gray-700">
                {t('orders.emailAddress')} <span className="text-red-500">*</span>
              </label>
              <input
                value={customer.email}
                onChange={(e) => setCustomer({ ...customer, email: e.target.value })}
                type="email"
                required
                className="w-full bg-white border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 text-left"
                placeholder={t('orders.emailPlaceholder')}
              />
            </div>

            {/* Phone (conditional) */}
            {(deliveryMethod === 'whatsapp' || deliveryMethod === 'phone') && (
              <div className="flex flex-col gap-1 text-left">
                <label className="block text-xs font-bold text-gray-700">
                  {t('orders.phoneNumber')} <span className="text-red-500">*</span>
                </label>
                <div className="flex gap-2">
                  <select
                    value={selectedCountryCode}
                    onChange={(e) => setSelectedCountryCode(e.target.value)}
                    className="w-24 bg-white border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
                  >
                    {countries.map((country) => (
                      <option key={country.code} value={country.code}>
                        {country.code}
                      </option>
                    ))}
                  </select>
                  <input
                    value={customer.phone}
                    onChange={(e) => setCustomer({ ...customer, phone: e.target.value })}
                    type="tel"
                    required
                    className="w-full bg-white border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 text-left"
                    placeholder={t('orders.phonePlaceholder')}
                    pattern="[567][0-9]{8}"
                    maxLength={9}
                  />
                </div>
              </div>
            )}
          </div>

          {/* Total display desktop */}
          <div className="hidden md:flex items-center justify-between pt-3 pb-6">
            <span>{t('orders.total')}</span>
            <div className="flex flex-col items-end">
              <span className="font-black text-lg text-gray-900">
                {currencyFormatter(totalPrice, currency)}
              </span>
              {hasDiscountVal && (
                <span className="text-sm line-through text-gray-400">
                  {currencyFormatter(originalPrice, currency)}
                </span>
              )}
            </div>
          </div>

          {/* Desktop submission button */}
          <button
            type="submit"
            className="btn-primary w-full hidden md:flex items-center justify-center mt-4 cursor-pointer"
            disabled={loading}
          >
            {loading ? (
              <i className="fa-solid fa-circle-notch fa-spin mr-2" />
            ) : (
              <span>{t('orders.placeOrder')}</span>
            )}
          </button>

          {/* Mobile bottom CTA actions */}
          {step === 1 && (
            <button
              type="button"
              onClick={() => setStep(2)}
              className="btn-primary w-full md:hidden mt-2 cursor-pointer"
            >
              {t('common.continue')}
            </button>
          )}

          {step === 2 && (
            <button
              type="submit"
              className="btn-primary w-full md:hidden mt-2 flex items-center justify-center cursor-pointer"
              disabled={loading}
            >
              {loading ? (
                <i className="fa-solid fa-circle-notch fa-spin mr-2" />
              ) : (
                <span>
                  {t('orders.placeOrder')} {currencyFormatter(totalPrice, currency)}
                </span>
              )}
            </button>
          )}

          {/* Mobile exclusive app rates caption */}
          <p className="text-[11px] text-gray-400 font-semibold text-center hidden md:block mt-2">
            {t('orders.appExclusiveRates')}
          </p>
        </form>
      ) : (
        <div className="text-center py-10 text-gray-500 text-sm font-medium">
          <i className="fa-light fa-wallet text-3xl text-gray-300 mb-3 block" />
          {t('orders.emptySummaryState')}
        </div>
      )}
    </div>
  );
};
