// GoSIM-WhiteLabel-Angular/src/app/components/progress-bar/progress-bar.component.ts
import { Component, Input, computed, signal } from '@angular/core';
import { NgClass, NgStyle } from '@angular/common';

@Component({
  selector: 'app-progress-bar',
  standalone: true,
  imports: [NgClass, NgStyle],
  template: `
    <div class="w-full bg-gray-200 rounded-full h-3">
      <div
        [ngClass]="[
          'h-3 rounded-full',
          progressPercent < 33 ? 'bg-red-500' : progressPercent < 66 ? 'bg-yellow-400' : 'bg-green-500'
        ]"
        [ngStyle]="{ width: progressPercent + '%' }"
      ></div>
    </div>
  `
})
export class ProgressBarComponent {
  @Input() progress: number = 0;
  @Input() maximum: number = 100;

  get progressPercent(): number {
    const val = (this.progress * 100) / this.maximum;
    return val === 0 ? 1 : val;
  }
}

// GoSIM-WhiteLabel-Vuejs/src/components/ProgressBar.vue
<template>
  <div class="w-full bg-gray-200 rounded-full h-3">
    <div
      :class="[
      'h-3 rounded-full',
      Progress < 33 ? 'bg-red-500' : Progress < 66 ? 'bg-yellow-400' : 'bg-green-500'
      ]"
      :style="{ width: Progress + '%' }"
    ></div>
  </div>
</template>
<script>
export default {
  name: "ProgressBar",
  props: {
    progress: {
      type: Number,
      required: true,
      default: 0,
    },
    maximum: {
      type: Number,
      required: true,
      default: 100,
    },
  },
  computed: {
    Progress() {
      return (this.progress * 100) / this.maximum == 0 ? 1 :(this.progress * 100) / this.maximum;
    },
  },
};
</script>
